# Generated by Django 3.2 on 2022-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactnumber',
            field=models.CharField(max_length=11),
        ),
    ]
