# Generated by Django 3.2 on 2022-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='blog')),
                ('blog_detail', models.TextField()),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
