# Generated by Django 3.2 on 2022-02-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadd',
            name='blog_date',
            field=models.DateTimeField(),
        ),
    ]
