# Generated by Django 3.2 on 2022-02-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogadd_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogadd',
            name='blog_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
